### ISSUE TITLE
Difference between this and ljharb/util.promisify

### ISSUE THREAD

**Issue by Deilan** [juliangruber/util-promisify#2]
What's the difference between this implementation and [ljharb/util.promisify](https://github.com/ljharb/util.promisify)?

**Comment by juliangruber** [comment]
This pretty much a 1:1 copy of what we have in node core, util.promisify diverges more in implementation it seems. You can compare the modules' sources with https://github.com/nodejs/node/blob/master/lib/internal/util.js#L201-L256.
