### ISSUE TITLE
license mismatch

### ISSUE THREAD

**Issue by anthonyronda** [juliangruber/util-promisify#7]
It appears as though your intent is to publish this package under the MIT license.

The text of your LICENSE file does not match the text of the MIT license. Instead it mentions a bunch of other packages as is commonly done in a [NOTICE](https://infra.apache.org/licensing-howto.html) file. Is this an error?

The package metadata crawler project [ClearlyDefined](https://clearlydefined.io/definitions/npm/npmjs/-/util-promisify/2.1.0) shows "discovered: Artistic-2.0 AND BSD-2-Clause AND BSD-3-Clause AND..." so I thought I'd ask.

**Comment by juliangruber** [comment]
Thank you so much for bringing this up! The reason that LICENSE file is there is that the code was mostly copied from Node.js's own source code. I assume therefore that we'll need a double license, is this right? Looking at your bio, do you want to help us out with this?

**Comment by anthonyronda** [comment]
I am not a lawyer, but I'd love to make suggestions. Virtually all of us reuse & redistribute licensed code, and helping each other reach a better understanding of our obligations (a good thing) amounts to "free legal advice" (the most expensive kind of legal advice). As such, I recommend doing your own research or consulting others to confirm my findings.

It appears as though you don't use code from the external libraries mentioned in the current license file. You will still have to keep the first two license notices (both MIT) in your files somewhere, since you use code from Node's repository. While that doesn't require your package to be licensed MIT, keep in mind that your existing users who have read your package.json are expecting it to be MIT licensed.

If you wish to use the convention Node uses, just add your own license with your own copyright notice to the top of the license file. Under this convention, your line 1-3 will read

```diff
+ util-promisify is licensed for use as follows:
+
+ """
```

This is followed by the full license text you choose. After that

```diff
+ """
+
- Node.js is licensed for use as follows:
+ This license applies to parts of util-promisify originating from the
+ https://github.com/nodejs/node/ repository:

"""
... THE MIT LICENSE TEXT FOR nodejs/node/ OMITTED FOR LENGTH ...
"""

- This license applies to parts of Node.js originating from the
+ This license applies to parts of util-promisify originating from the
https://github.com/joyent/node repository:

"""
```

 I also recommend removing the license notices for externally maintained libraries you aren't using, because that caused some confusion about your package (verify you aren't using them).

This isn't my favorite way of doing things, but it's clear and concise for human readers, and following Node's lead here might be the most comfortable approach for you. There are FOSS licensing specifications that are better for automatic tools. I like [REUSE](https://reuse.software/spec/), but as far as I know there's no dominant license spec in Node-land. The Apache specification in my top comment is another example.

**Comment by juliangruber** [comment]
Thank you so much, that was very clear for me to follow <3

Could you take a look at this PR I created? https://github.com/juliangruber/util-promisify/pull/8
